version: '3.8'

services:
  persian-legal-ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: persian-legal-ai
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/app/data/database.sqlite
      - PORT=8080
      - LOG_LEVEL=info
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - persian-legal-network

  # Optional: Redis for caching (if available)
  redis:
    image: redis:7-alpine
    container_name: persian-legal-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - persian-legal-network
    profiles:
      - with-redis

volumes:
  redis-data:
    driver: local

networks:
  persian-legal-network:
    driver: bridge