version: '3.8'

# Development overrides for docker-compose.yml
services:
  backend-dev:
    environment:
      - NODE_ENV=development
      - PORT=3000
      - SERVER_PORT=3000
      - SQLITE_PATH=/data/app.sqlite
      - DATABASE_PATH=/data/app.sqlite
      - JWT_SECRET=dev_jwt_secret_not_for_production
      - CORS_ORIGIN=http://localhost:5173
    volumes:
      - ./server:/app/server
      - ./database.sqlite:/app/database.sqlite
      - sqlite_data:/data
      - app_logs:/app/logs
      - node_modules_be:/app/node_modules
    command: ["node", "--watch", "server/index.js"]
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s

  frontend-dev:
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
      - VITE_WS_URL=ws://localhost:3000
      - VITE_HMR_PORT=5173
    volumes:
      - .:/app
      - node_modules_fe:/app/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5173"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s