version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    image: persian-legal-ai:latest
    container_name: persian-legal-ai
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_PATH=/data/persian_legal_ai.sqlite
      - SQLITE_PATH=/data/persian_legal_ai.sqlite
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173
    volumes:
      - ./var/data:/data
      - ./var/logs:/logs
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS --max-time 5 http://localhost:3000/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped
    networks:
      - persian-legal-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  persian-legal-net:
    driver: bridge
    name: persian-legal-network

volumes:
  data:
    driver: local
  logs:
    driver: local