version: '3.8'

services:
  persian-legal-ai-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: persian-legal-ai-dev
    ports:
      - "8080:8080"
      - "5173:5173"  # Vite dev server
    environment:
      - NODE_ENV=development
      - DATABASE_PATH=/app/data/database.sqlite
      - PORT=8080
      - LOG_LEVEL=debug
      - VITE_API_BASE=http://localhost:8080/api
    volumes:
      - .:/app
      - /app/node_modules
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    command: ["npm", "run", "dev"]
    networks:
      - persian-legal-dev-network

  # Development database
  postgres-dev:
    image: postgres:15-alpine
    container_name: persian-legal-postgres-dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=persian_legal_dev
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - persian-legal-dev-network
    profiles:
      - with-postgres

  # Development Redis
  redis-dev:
    image: redis:7-alpine
    container_name: persian-legal-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis-dev-data:/data
    restart: unless-stopped
    networks:
      - persian-legal-dev-network
    profiles:
      - with-redis

volumes:
  postgres-dev-data:
    driver: local
  redis-dev-data:
    driver: local

networks:
  persian-legal-dev-network:
    driver: bridge
