version: '3.9'

# Development overrides for hot-reload and debugging
services:
  # Backend with hot reload
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: builder
    volumes:
      - ./server:/app/server:ro
      - ./public:/app/public:ro
      - ./package.json:/app/package.json:ro
      - ./package-lock.json:/app/package-lock.json:ro
      - node_modules_be:/app/node_modules
      - sqlite_data:/data
      - app_logs:/logs
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_PATH: /data/database.sqlite
      SQLITE_PATH: /data/database.sqlite
      JWT_SECRET: dev_jwt_secret_not_for_production
      CORS_ORIGIN: http://localhost:5173,http://localhost:3000,http://localhost
      DEBUG: "express:*"
    command: ["npx", "nodemon", "--watch", "server", "--ext", "js,ts,json", "server/main.js"]
    profiles:
      - dev

  # Frontend with Vite HMR
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - ./src:/app/src:ro
      - ./public:/app/public:ro
      - ./index.html:/app/index.html:ro
      - ./vite.config.ts:/app/vite.config.ts:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - ./tsconfig.app.json:/app/tsconfig.app.json:ro
      - ./tailwind.config.cjs:/app/tailwind.config.cjs:ro
      - ./postcss.config.cjs:/app/postcss.config.cjs:ro
      - node_modules_fe:/app/node_modules
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:3000
      VITE_WS_URL: ws://localhost:3000
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
    stdin_open: true
    tty: true
    profiles:
      - dev

  # Redis for development
  redis:
    environment:
      REDIS_LOGLEVEL: debug
    command: redis-server --appendonly yes --loglevel debug
    profiles:
      - dev

volumes:
  sqlite_data:
    driver: local
  app_logs:
    driver: local
  redis_data:
    driver: local
  node_modules_be:
    driver: local
  node_modules_fe:
    driver: local